import{n as l}from"./assets/vendor-BY9c7rfI.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const c=()=>JSON.parse(localStorage.getItem("tasks")),d=t=>{const s=c()||[];s.push(t),localStorage.setItem("tasks",JSON.stringify(s))},m=t=>{localStorage.setItem("theme",t)},i={headerForm:document.querySelector(".header-form"),taskList:document.querySelector("#task-list"),themeBtn:document.querySelector("#themeToggle")},u=t=>{const s=t.map(({id:n,taskNameValue:o,taskDescriptionValue:e})=>`<li class="task-list-item">
      <button class="task-list-item-btn">Delete</button>
      <h3>${o}</h3>
      <p>${e}</p>
  </li>`).join("");i.taskList.innerHTML=s},f=({id:t,taskNameValue:s,taskDescriptionValue:n})=>{i.taskList.insertAdjacentHTML("beforeend",`<li class="task-list-item" >
      <button class="task-list-item-btn data-id=${t}">Delete</button>
      <h3>${s}</h3>
      <p>${n}</p>
  </li>`)},h=t=>{t.preventDefault();const{taskName:s,taskDescription:n}=t.target.elements,o=s.value.trim(),e=n.value.trim();if(!o||!e)return;const r={id:l(),taskNameValue:o,taskDescriptionValue:e};d(r),f(r),t.target.reset()},p=t=>{t.target.nodeName},k=()=>{const t=c();u(t)};function g(t){const s=document.body.classList.contains("theme-dark"),n=s?"theme-light":"theme-dark";document.body.classList.replace(s?"theme-dark":"theme-light",n),m(n)}document.addEventListener("DOMContentLoaded",k);i.headerForm.addEventListener("submit",h);i.taskList.addEventListener("click",p);i.themeBtn.addEventListener("click",g);
//# sourceMappingURL=index.js.map
